# docker-compose for backend, frontend, db, worker
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tracker
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend
    container_name: backend
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:postgres@db:5432/tracker
      SECRET_KEY: your_super_secret_key
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "5173:5173"
    command: npm run dev -- --host
    volumes:
      - ./frontend:/app
    working_dir: /app
    depends_on:
      - backend

  worker:
    build:
      context: ./worker
    container_name: worker
    command: python main.py
    volumes:
      - ./worker:/app
    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:postgres@db:5432/tracker
    depends_on:
      - db

volumes:
  postgres_data:
